apiVersion: v1
kind: Secret
metadata:
  name: opsnexus-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opsnexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-host: {{ .Values.database.host | quote }}
  db-port: {{ .Values.database.port | quote }}
  db-user: {{ default "opsnexus" .Values.database.user | quote }}
  db-password: {{ default "changeme" .Values.database.password | quote }}
